name: Deploy to production
run-name: ${{ github.actor }} Deploy to production 🚀
on:
  push:
    branches:
      - main
jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Workaround for Wix CLI
        run: mkdir -p ~/.wix/auth && echo $USER_AUTH_ACCOUNT > ~/.wix/auth/account.json
        env:
          USER_AUTH_ACCOUNT: ${{ secrets.USER_AUTH_ACCOUNT }}

      - name: CLI pull env
        if: github.event_name != 'pull_request'
        run: |
          yarn wix astro pull-env --prod

      - name: CLI pull env
        if: github.event_name == 'pull_request'
        run: |
          yarn wix astro pull-env

      - name: Build
        run: |
          yarn build

      - name: Deploy PROD
        if: github.event_name != 'pull_request'
        run: |
          yarn wix astro deploy --prod

      - name: Deploy Preview
        if: github.event_name == 'pull_request'
        run: |
          yarn wix astro deploy

      - name: Comment PR with deploy preview link
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_
          comment-tag: deploy-preview-link
