name: Build and Deploy
run-name: ${{ github.actor }} Build and Deploy 🚀
on:
  push:
    branches:
      - "*" # Triggers on all branches for push events
jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Auth CLI
        run: |
          yarn wix login --api-key $CLI_API_KEY
        env:
          CLI_API_KEY: ${{ secrets.CLI_API_KEY }}

      - name: CLI pull env
        if: github.ref_name == 'main' || github.ref_name == 'master'
        run: |
          yarn wix astro pull-env production


      - name: Fetch PR number using GitHub API
        id: get-pr
        run: |
          pr_number=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:$GITHUB_REF_NAME" \
            | jq -r '.[0].number')
          echo "PR_NUMBER=${pr_number}" >> $GITHUB_ENV

      - name: CLI pull env
        if: github.ref_name != 'main' && github.ref_name != 'master'
        run: |
          yarn wix astro pull-env pr-$PR_NUMBER

      - name: Build
        run: |
          yarn build

      - name: Deploy production
        if: github.ref_name == 'main' || github.ref_name == 'master'
        run: |
          yarn wix astro deploy --prod

      - name: Deploy preview
        id: deploy-preview
        if: github.ref_name != 'main' && github.ref_name != 'master'
        run: |
          output=$(yarn wix astro deploy --env pr-$PR_NUMBER)
          echo "deploy-output=${output}" >> "$GITHUB_OUTPUT"

      - name: Comment PR with deploy preview output
        if: github.ref_name != 'main' && github.ref_name != 'master'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
             ${{ join(steps.deploy-preview.outputs.output, ' ') }}
          comment-tag: deploy-preview-output
