name: Deploy to production
run-name: ${{ github.actor }} Deploy to production 🚀
on:
  push:
    branches:
      - main
jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Auth CLI
        run: |
          yarn wix login --api-key $CLI_API_KEY
        env:
          CLI_API_KEY: ${{ secrets.CLI_API_KEY }}
          WIX_CLI_TEST_OVERRIDES: "{\"inkDebug\": true}"
          DEBUG: "*"
