name: Deploy

on: 
  pull_request:

jobs:
  deploy:
    uses: ./.github/workflows/wixstro-preview.yaml
    with:
      name: pr-${{ github.event.number }}
      ref: ${{ github.context.ref }}
    secrets:
      wix-api-key: ${{ secrets.CLI_API_KEY }}

