name: Wixstro

on: 
  pull_request:

jobs:
  deploy:
    strategy:
      matrix:
        include: 
          - ref: ${{ github.context.ref }}
            title: Merge Commit
            env-name: pr-${{ github.event.number }}
          - ref: ${{ github.event.pull_request.head.sha }}
            title: Head Commit
            env-name: ${{ github.event.pull_request.head.ref }}
    uses: ./.github/workflows/wixstro-deploy.yaml
    name: Preview of ${{ matrix.title }}
    with:
      env-name: ${{ matrix.env-name }}
      title: ${{ matrix.title }}
      ref: ${{ github.context.ref }}
    secrets:
      wix-api-key: ${{ secrets.CLI_API_KEY }}

  pr-comment:
    name: Preview Comment on Pull Request
    needs: deploy
    steps:
      - name: Comment PR with deploy output
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ## Deployment - ${{ matrix.title }}
            ${{ join(needs.deploy.outputs.deploy-result, ' ') }}
          comment-tag: deploy-preview-output-${{ matrix.env-name }}
    

